# Generated by Django 5.2.5 on 2025-09-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
            ],
        ),
    ]
