# Generated by Django 5.2.5 on 2025-09-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, null=True, verbose_name='Миниатюра'),
        ),
    ]
