# Generated by Django 5.2.5 on 2025-09-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название видео'),
        ),
    ]
